
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  walletstore:

networks:
  peer.com:
    name: test

services:

  explorer.peer.com:
    image: hyperledger/explorer:latest
    container_name: explorer.peer.com
    hostname: explorer.peer.com
    environment:
      - DATABASE_HOST=explorerdb.peer.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=${PORT:-8080}
    volumes:
      - ./explorer-config/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer-config/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./organizations:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    networks:
      - peer.com 
